FROM daptin/daptin
COPY schema_todo_daptin.yml /opt/daptin/schema_todo_daptin.yml
COPY data/initial.json /data/initial.json
COPY js /site/js
COPY node_modules /site/node_modules
COPY index.html /site/index.html